# Generated by Django 4.0.4 on 2022-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('agua', models.IntegerField(default=0)),
                ('alimentacao', models.IntegerField(default=0)),
                ('medicacao', models.IntegerField(default=0)),
                ('municao', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=5)),
            ],
        ),
    ]
