# Generated by Django 4.0.4 on 2022-04-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='agua',
            field=models.IntegerField(),
        ),
    ]
