# Generated by Django 4.0.4 on 2022-04-15 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0003_alter_sobrevivente_alimentacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobrevivente',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='alimentacao',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='medicacao',
        ),
        migrations.RemoveField(
            model_name='sobrevivente',
            name='municao',
        ),
        migrations.AddField(
            model_name='sobrevivente',
            name='is_infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='sobreviventes.sobrevivente')),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='sobreviventes.sobrevivente')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agua', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('alimentacao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('medicacao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('municao', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sobrevivente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='sobreviventes.sobrevivente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reports',
            constraint=models.UniqueConstraint(fields=('reported', 'reporting'), name='report'),
        ),
    ]
