# Generated by Django 4.0.4 on 2022-04-15 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0004_remove_sobrevivente_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=5, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
