# Generated by Django 4.0.4 on 2022-04-15 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobreviventes', '0005_alter_sobrevivente_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrevivente',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='sobrevivente',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
